[package]
name = "pretty-class"
version = "0.1.0"
authors = ["xavil <max.duzen@gmail.com>"]
edition = "2018"

[dependencies]
ansi_term = "0.11.0"
structopt = "0.2.14"
petgraph = "0.4.13"

[dependencies.class]
path = "../class"
version = "*"
